"""Credential encryption, gateway key hashing, and outbound URL safety checks."""
import base64
import hashlib
import ipaddress
import secrets
import socket
from urllib.parse import urlparse

from cryptography.fernet import Fernet, InvalidToken

from .config import get_settings


def _fernet() -> Fernet:
    key = get_settings().encryption_key.strip()
    try:
        return Fernet(key.encode())
    except ValueError:
        # Not a Fernet key (for example a value generated by Render): derive one from it.
        return Fernet(base64.urlsafe_b64encode(hashlib.sha256(key.encode()).digest()))


def encrypt(value: str) -> str:
    return _fernet().encrypt(value.encode()).decode()


def decrypt(value: str | None) -> str | None:
    if not value:
        return None
    try:
        return _fernet().decrypt(value.encode()).decode()
    except InvalidToken:
        return None


def mask(value: str | None) -> str | None:
    if not value:
        return None
    return "••••" + value[-4:]


def new_gateway_key() -> tuple[str, str, str]:
    """Return (full key shown once, display prefix, sha256 hash stored)."""
    raw = "plumb_" + secrets.token_urlsafe(32)
    return raw, raw[:12], hash_key(raw)


def hash_key(raw: str) -> str:
    return hashlib.sha256(raw.encode()).hexdigest()


class UnsafeURL(ValueError):
    pass


def check_outbound_url(url: str) -> None:
    """Reject URLs that point at private networks, to stop the backend being used for SSRF."""
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https") or not parsed.hostname:
        raise UnsafeURL("Use a full http:// or https:// address")
    if get_settings().allow_private_endpoints:
        return
    try:
        infos = socket.getaddrinfo(parsed.hostname, parsed.port or (443 if parsed.scheme == "https" else 80))
    except socket.gaierror:
        raise UnsafeURL(f"Could not resolve {parsed.hostname}")
    for info in infos:
        ip = ipaddress.ip_address(info[4][0])
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved or ip.is_multicast:
            raise UnsafeURL("This address points to a private network, which Plumb can't call")
